interface ProductItem {
  id: string;
  name: string;
  category: "quimicos" | "equipos";
  categoryLabel: string;
  brand: string;
  desc: string;
  versions: string[];
  price: string;
  image: string;
}

export const products: ProductItem[] = [
    {
      id: "cloro-poolquim",
      name: "Cloro en Polvo, Pastilla y Granulado",
      category: "quimicos",
      categoryLabel: "Químicos",
      brand: "Poolquim",
      desc: "Cloro de alta pureza diseñado para la desinfección total y mantenimiento microbiológico del agua. Elimina bacterias, hongos y algas.",
      versions: ["1 Kilo", "5 Kilos", "Cuñete 50 Kilos"],
      price: "A cotizar",
      image: "/images/cloro.jpeg",
    },
    {
      id: "ph-mas-poolquim",
      name: "pH + Elevador de pH",
      category: "quimicos",
      categoryLabel: "Químicos",
      brand: "Poolquim",
      desc: "Producto balanceador formulado para aumentar el pH del agua cuando se encuentra en niveles ácidos, evitando irritación en piel y ojos.",
      versions: ["1 Kilo", "5 Kilos", "Cuñete 50 Kilos"],
      price: "A cotizar",
      image: "/images/ph-plus.jpg",
    },
    {
      id: "ph-menos-poolquim",
      name: "pH - Reductor de pH",
      category: "quimicos",
      categoryLabel: "Químicos",
      brand: "Poolquim",
      desc: "Compuesto químico diseñado para disminuir niveles altos de pH y alcalinidad total, asegurando que el cloro trabaje al 100% de eficiencia.",
      versions: ["1 Kilo", "5 Kilos", "Cuñete 50 Kilos"],
      price: "A cotizar",
      image: "/images/ph-less.jpg",
    },
    {
      id: "floculante-flokant",
      name: "Floculante Clarificador Líquido",
      category: "quimicos",
      categoryLabel: "Químicos",
      brand: "Flokant",
      desc: "Clarificador y coagulante de alto rendimiento. Aglutina sedimentos y micropartículas suspendidas haciéndolas precipitar para su aspirado.",
      versions: ["1 Litro", "10 Litros", "50 Litros"],
      price: "A cotizar",
      image: "/images/floculante.jpeg",
    },
    {
      id: "carrito-aspirador",
      name: "Carrito Aspiradora de Fondo",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Carro barredora manual diseñado para acoplar al maneral y succionar sedimentos, lodo y suciedad depositada en el fondo de la piscina.",
      versions: ["Estándar"],
      price: "A cotizar",
      image: "/images/carrito-aspiradora.jpg",
    },
    {
      id: "manguera-flexible",
      name: "Manguera de Aspiración Flexible",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Manguera flotante de alta flexibilidad y resistencia a la intemperie y aplastamiento, ideal para interconectar la barredora con la succión.",
      versions: ["Diferentes tamaños"],
      price: "A cotizar",
      image: "/images/manguera-alberca.jpg",
    },
    {
      id: "maneral-aluminio",
      name: "Maneral Telescópico de Aluminio",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Tubo telescópico extensible de aluminio anodizado, ligero y resistente, compatible con redes, cepillos y barredoras.",
      versions: ["Medida Ajustable"],
      price: "A cotizar",
      image: "/images/maneral-alberca.jpg",
    },
    {
      id: "cepillo-muros",
      name: "Cepillo para Paredes y Pisos",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Cepillo de cerdas de nylon reforzado de alta densidad, idóneo para tallar y desprender algas o sarro en muros y rincones.",
      versions: ["Estándar"],
      price: "A cotizar",
      image: "/images/cepillo-alberca.jpg",
    },
    {
      id: "reactivos-parametros",
      name: "Kit de Reactivos de Medición",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Kit analizador químico por reactivos líquidos para monitorear con rapidez y exactitud los niveles de Cloro libre y pH en el agua.",
      versions: ["Estándar"],
      price: "A cotizar",
      image: "/images/analizador-quimico.jpg",
    },
    {
      id: "red-sacahojas",
      name: "Red Sacahojas de Superficie y Fondo",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Red reforzada con malla cerrada de nylon de alta durabilidad para la recolección ágil de hojas, insectos y basura flotante.",
      versions: ["Plana / Con Bolsa"],
      price: "A cotizar",
      image: "/images/red-alberca.jpg",
    },
    {
      id: "flotador-pastillas",
      name: "Flotador Dosificador de Cloro",
      category: "equipos",
      categoryLabel: "Equipos y Accesorios",
      brand: "Básico",
      desc: "Dispensador flotante con anillo regulador de disolución lenta, apto para pastillas de cloro compactas de 3 pulgadas.",
      versions: ["Regulable"],
      price: "A cotizar",
      image: "/images/flotador-alberca.jpg",
    }
  ];
