export const projects = [
    {
      id: 1,
      title: "Piscina Residencial Vista Verde",
      category: "residencial",
      categoryLabel: "Residencial",
      desc: "Limpieza profunda y mantenimiento automatizado semanal en jardín residencial.",
      image: "/images/backyard_pool.png",
      location: "San Pedro Garza",
    },
    {
      id: 2,
      title: "Infinity Pool - Villa Atardecer",
      category: "residencial",
      categoryLabel: "Residencial",
      desc: "Balance químico y puesta a punto de piscina infinita con desbordamiento finlandés.",
      image: "/images/luxury_pool.png",
      location: "Valle de Bravo",
    },
    {
      id: 3,
      title: "Piscina Olímpica - Club Deportivo",
      category: "comercial",
      categoryLabel: "Comercial",
      desc: "Mantenimiento químico intensivo diario y diagnóstico de sistemas de bombeo industriales.",
      image: "/images/hero.png",
      location: "Polanco, CDMX",
    },
    {
      id: 4,
      title: "Puesta a Punto - Residencia Coyoacán",
      category: "residencial",
      categoryLabel: "Residencial",
      desc: "Rehabilitación de agua estancada y remoción profunda de sarro en mosaicos.",
      image: "/images/fondo-inicio.jpeg",
      location: "Coyoacán, CDMX",
    },
    {
      id: 5,
      title: "Mantenimiento Hotel Boutique Aqua",
      category: "comercial",
      categoryLabel: "Comercial",
      desc: "Servicio premium de mantenimiento integral preventivo y balance de cloro automatizado.",
      image: "/images/chubby_man_cleaning_pool.png",
      location: "Cuernavaca, Mor.",
    },
  ];
